# Generated by Django 6.0.6 on 2026-06-25 16:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('series_multiplier', models.FloatField()),
                ('repetitions_multiplier', models.FloatField()),
            ],
            options={
                'db_table': 'fitness_level',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'limitation',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='MuscularArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'muscular_area',
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'routine',
            },
        ),
        migrations.CreateModel(
            name='GymUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'gym_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym_core.machine')),
                ('muscular_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_core.musculararea')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_frequency', models.PositiveIntegerField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_core.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plan',
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.trainingplan')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_core.routine')),
            ],
            options={
                'db_table': 'workout_log',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.exercise')),
                ('limitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.limitation')),
            ],
            options={
                'db_table': 'exercise_limitation',
                'constraints': [models.UniqueConstraint(fields=('exercise', 'limitation'), name='unique_exercise_limitation')],
            },
        ),
        migrations.CreateModel(
            name='GoalRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.goal')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.routine')),
            ],
            options={
                'db_table': 'goal_routine',
                'constraints': [models.UniqueConstraint(fields=('goal', 'routine'), name='unique_goal_routine')],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField()),
                ('repetitions', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.routine')),
            ],
            options={
                'db_table': 'routine_exercise',
                'constraints': [models.UniqueConstraint(fields=('routine', 'exercise'), name='unique_routine_exercise')],
            },
        ),
        migrations.CreateModel(
            name='PlanRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveIntegerField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.routine')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.trainingplan')),
            ],
            options={
                'db_table': 'plan_routine',
                'constraints': [models.UniqueConstraint(fields=('plan', 'routine', 'session_number'), name='unique_plan_routine_session')],
            },
        ),
        migrations.CreateModel(
            name='UserAreaFitnessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_core.fitnesslevel')),
                ('muscular_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.musculararea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_area_fitness_level',
                'constraints': [models.UniqueConstraint(fields=('user', 'muscular_area'), name='unique_user_muscular_area')],
            },
        ),
        migrations.CreateModel(
            name='UserLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('limitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_core.limitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_limitation',
                'constraints': [models.UniqueConstraint(fields=('user', 'limitation'), name='unique_user_limitation')],
            },
        ),
    ]
