# Generated by Django 6.0.6 on 2026-06-30 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='routine',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='plan_routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='gym_core.planroutine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
