# Generated by Django 6.0.6 on 2026-07-06 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_core', '0002_auto_20260702_1501'),
        ('gym_core', '0002_remove_workoutlog_plan_remove_workoutlog_routine_and_more'),
    ]

    operations = [
    ]
